### ISSUE TITLE
THE CUSTOM FORMAT PAGE GOES BACK UNEXPECTEDLY

### ISSUE THREAD

**Issue by beckysophie** [0xpr03/VocableTrainer-Android#28]
***Expected Behavior***

It should allow users adjust the custom format settings on landscape mode 

***Actual Behavior***

Each time the app gets to the custom format page, and the device is rotated, the app goes back unexpectedly 

***How to produce the bug***

* Open the app 
* Click on import 
* Click on the more option icon at the top right corner 
* Select Edit Custom Format 

* Now rotate screen, such that you should adjust some settings on landscape mode 

* The app would always go back to the import page , Thereby disallowing users from using it 
 

***TEST TOOLS***

* Operating system : Android 6.0
* Phone : Infinix hot s
* Vocable App Trainer v0.5.3

***Recording of the bug is showned below......***

Watch the video below to see how it behaves.... 

https://youtu.be/9T8NiWpkN-8

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@beckysophie/the-custom-format-page-goes-back-unexpectedly">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by sachincool** [comment]
Hey, @0xpr03 I am a Community Manager from Utopian-io. Just checking in to know if you are happy with the reports sent by Utopian-io?  
* If not, we like to know your opinion on what kind of reports you would like.
* Are these reports Descriptive enough?
As Utopian's main motive is for the PO's to be a part of Us.
Please, know that you get a high respect and scoring ability for the posts made on your project. 
you can submit your development, milestones achieved on utopian and get reward for your hard-work and showcase other developers.

If you don't want reports from utopian-io, you can opt-out. by sending us a ticket on our https://support.utopian.io

**Comment by 0xpr03** [comment]
@sachincool 
Hi.
I'm not really happy with the current state. (and the same goes for others [1] )
First of all this report starts with CAPS all the way, which won't bring me to handle it earlier then others,  probably less. (Even more when I've #23 going on which will change nearly everything.) Also in #25 it got a bit rude.

What I would like to see are mass-reports. As this utopian seems to find out, my app doesn't really handle androids quirk regarding viewport changes that well. Instead of opening one Bug for everything #26,#27,#28 (and kind of #25 ) they could open up one issue gathering all bugs. If the argument is money I'll happily block further reports & one should question utopian.
None of the users I know reported that bug before and I know some of them personally. So all in all just noise about a technical bug which could be gathered into one report.

Also I would require from utopians to use logact for android. Logcat includes all dev-log prints as well as crash reports with stacktraces. This could help [a lot](https://github.com/HoraApps/LeafPic/issues/538).
Utopians should be able to provide at least so much of support as they're getting money for that and once setup you don't have to do much anymore for future reports to gather logs. (And filter those logs, android studio can do this out of the box, I don't care for the noise of your other apps.)
What also should change are descriptions lacking the [crucial part](https://github.com/0xpr03/VocableTrainer-Android/issues/24), here someone just found a workaround for starting without a valid list of items, I could see that in the video but not in his description. I like the fallback of a video but not the requirement of watching one to understand what happened.

Please [no gifs](https://github.com/SimpleMobileTools/Simple-Clock/issues/11) in reports, link to a video if you need one as backup for your description. (Bandwidth, distraction, space, performance,..)

I personally will start to block accounts like [this one](https://github.com/PeerzadaZeeshan?tab=overview&from=2018-03-01&to=2018-03-31) with no contribution but only [minor](https://github.com/JohnLines/mediclog/issues/15) [stuff](https://github.com/SimpleMobileTools/Simple-Calendar/issues/417), where [requests for more information](https://github.com/vijai1996/screenrecorder/issues/44) won't get any response. Somebody takes his time to look into that reports, probably [writes a lot](https://github.com/JohnLines/mediclog/issues/14#issuecomment-376488507) to provide context and help. While the person on the other end just wants money and rushes to the next app.
I want to care about the report, I want to help my userbase but I don't want to be the free workforce for someone else getting money by abusing my app and finding a (hopefully at least) technically correct bug without caring about it in any way. I could use my time and fix bugs / implement features for my real userbase / make my own money for living by doing my work in that time.

What you're currently ending up with, is [this](https://github.com/SimpleMobileTools/Simple-Clock/issues/14#issuecomment-376897561):
> [..] many reports from utopian are crap as they do it just for the reward[..]

Leading to #25 where out of greed the tone of speech is going harsh to reach the goal. It might have been that there is a real bug behind the report, but that's getting drowned in mass reports & fights over not-invalid. Overall this causes harm, even if some minor bugs are found.
Because in the end this is just a hobby of mine, I'm not getting any money, other reports will get drowned and I will stop taking enough time for reports.

Or to reflect most reports here:
Where is my money for writing up this "article" ?

[1]
https://github.com/jensstein/oandbackup/issues/202#issuecomment-377673751
https://github.com/OGRECave/ogre/issues/689

**Comment by techslut** [comment]
Hi @0xpr03 !

Thank you for you insights. They mean a lot and we'll be sure to take them into advisement our next update to the platform and guidelines. We'll absolutely add a demand for logs like you specified as we continue to make efforts to assure the quality of the work rewarded.

I apologize for the inconvenience as we learn and grow, and welcome you to join our Discord server (if you can spare the time) so we can chat about how you think Utopian can help you and your project. Alternatively, we can add your project to our blacklist to prevent contributors from submitting contribution via Utopian in hopes of receiving a potential reward.

Thank in advance!
- Ilana
